### ISSUE TITLE
Rename dest file

### ISSUE THREAD

**Issue by mgohin** [GaelGirodon/markdown-to-document#1]
With the `--dest` option, we can only provide a directory. 

Would be nice to have an option or an enhancement of the `--dest` option to be able to rename the destination file. It'll prevent user to user more libs to move, rename or delete files.

My case is to compile `README.md` to `dist/index.html`.

And thanks for your lib, it's pretty nice ;)

**Comment by GaelGirodon** [comment]
Thanks for opening this issue, I agree that it would be useful to add this kind of feature.

However, it can be a bit tricky to implement. If I change the behavior of the `--dest` option, renaming the output file will be available if there's only one source file (for bulk processing, we would need some kind of output filename pattern). The tool must also be able to assert whether `--dest` option value should be used as a directory or as an output filename (`--dest` option value ends with `.html`?). I wouldn't want to add this kind of inconsistent behavior to the CLI. Do you see a better way to implement this feature?

I'm glad to see that this tool is used by other people :)

**Comment by mgohin** [comment]
I guess you could add a file name template option ? And you provide only an index number as parameter to do something light for now ?

> I'm glad to see that this tool is used by other people :)

My pleasure, it's easy and it works :)

**Comment by GaelGirodon** [comment]
I'm pretty busy right now so I won't be able to release this feature very quickly.

Until this feature is implemented, you could use the following workaround:

```bash
mdtodoc README.md --dest dist/ && mv dist/README.html dist/index.html
```

This solution won't work with the _watch_ feature, but at least, it will do the job for simple compilations and it doesn't require any additional library, just some _good old Bash/Shell_ 😉

**Comment by mgohin** [comment]
Because I use `cpy-cli` for other purposes in my build, I use it to rename the file

    cpy README.html ./dist --rename=index.html

(PS: sont toujours sous l'eau ces Toulousains 😄)

**Comment by GaelGirodon** [comment]
It requires an additional library but if you're already using it in your build process, that's okay!

PS : je ne saurais pas dire si c'est une spécialité de la région, est-ce vraiment plus tranquille du côté de Bordeaux ? 😄

**Comment by mgohin** [comment]
Ho tu sais ici, c'est tranquille 😃
