### ISSUE TITLE
text in mermaid diagrams show incomplete

### ISSUE THREAD

**Issue by hallkk** [GaelGirodon/markdown-to-document#3]
## env
docker: node:lts-alpine3.10

## cli 
`mdtodoc open_doc.md -l "page" -t "github" -s "atom-one-light" --numbered-headings --code-copy --mermaid`
## image

![image](https://user-images.githubusercontent.com/1014928/97156944-615c7980-17b2-11eb-8362-5d359ad167f4.png)
 

PS: diagram render correctly On win10 & v12.19.0 of same command

![image](https://user-images.githubusercontent.com/1014928/97157136-abddf600-17b2-11eb-91a3-c50081e41260.png)

**Comment by GaelGirodon** [comment]
I don't think that this rendering issue is linked to _Markdown To Document_ because this tool only does two things for enabling _mermaid_ diagrams support:

1. It compiles Markdown fenced code blocks (` ```mermaid `) to the correct HTML tags so that _mermaid_ can handle them, e.g.:

```html
<pre class="mermaid-block">
<code class="language-mermaid mermaid">graph LR
    Markdown -- mdtodoc --&gt; HTML
</code>
</pre>
```

2. It includes the _mermaid_ library in the output HTML document as a `script` tag

The actual diagram rendering is done directly by the _mermaid_ library when you open the HTML document in your web browser.
