### ISSUE TITLE
Syntax highlighting not colouring code block

### ISSUE THREAD

**Issue by inspiraller** [GaelGirodon/markdown-to-document#4]
**When I run this command:**
mdtodoc markdownfiles/*.md --dest dist --theme github --highlight-style atom-one-light,

I get no syntax highlighting for my code blocks
I would expect this to have syntax colouring for my html and javascript as below.

Example.md
# Some js file stuf here 
```js
const x = "hello"
console.log(x)
```

# Some html stuff here...
```html
<!doctype html>
<html lang="en">
<body>
  <div id="app">Placeholder.</div>

  <script>
    // do something here...
    document.getElementById('app').innerHTML = 'hello world';
  </script>
</body>
</html>
```

**Comment by GaelGirodon** [comment]
Duplicates #5
