### ISSUE TITLE
them - solarized dark  - as suggested in your documentation causes error

### ISSUE THREAD

**Issue by inspiraller** [GaelGirodon/markdown-to-document#6]
Your documentation themes do not work for me and solarized dark causes an actual error

The --highlight-style option can receive the name of a [Hightlight.js style](https://github.com/highlightjs/highlight.js/tree/master/src/styles) (file name without extension, e.g. solarized-dark) or the path to a custom style file (a local path or a HTTP URL).

> docs@1.0.0 mdtodoc
> mdtodoc markdownfiles/*.md --dest dist --theme github --highlight-style solarized-dark --layout layout/custom-layout.html

Error: Invalid highlight style 'solarized-dark': file not found or not readable.
    at Style.validate (file:///C:/site/docs/node_modules/markdown-to-document/src/style.js:177:13)
    at async Style.loadHighlightStyle (file:///C:/site/docs/node_modules/markdown-to-document/src/style.js:160:19)
    at async Style.init (file:///C:/site/node_modules/markdown-to-document/src/style.js:77:28)
    at async Processor.process (file:///C:/site/docs/node_modules/markdown-to-document/src/processor.js:63:5)

**Comment by GaelGirodon** [comment]
Only highlight styles located at the root of the `styles/` directory of Hightlight.js can be provided without a full path: <https://www.jsdelivr.com/package/npm/highlight.js?path=styles>. It seems that `solarized-dark` has been moved to the subfolder `base16/` in a later version of Highlight.js. So you can:

- Use a "root" Highlight.js style: `monokai`, `github`, ...
- Provide the full path or URL to the CSS file you want to use, e.g. <https://cdn.jsdelivr.net/npm/highlight.js@11.6.0/styles/base16/solarized-dark.css>
- Wait for a future release of Markdown To Document where I will allow to use by name Highlight.js styles located in the `base16/` subfolder (thanks for pointing out the issue) 🙂
